version: "3.8"
services:
    db:
        image: postgres:16-alpine
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: selabdb
    phpmyadmin:
        image: adminer
        depends_on:
            - db
        ports:
            - 9000:8080
    backend:
        image: mansmooth/se331-backend:latest
        ports: 8999:8080
        restart: always
        environment:
            - JAVA_PROFILE=prod,db
        depends_on:
            - db
