spring:
    datasource:
        url: jdbc:postgresql://db:5432/selabdb
        username: root
        password: password
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: create
    servlet:
        multipart:
            max-file-size: 10MB
application:
    security:
        jwt:
            expiration: 86400000
            refresh-token:
                expiration: 604800000
firebase:
    bucket: am-l-4b665.appspot.com
