spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/selabdb
        username: root
        password: password
    jpa:
        properties:
            hibernate:
                jdbc:
                    lob:
                        "[non_contextual_creation]": true
        hibernate:
            ddl-auto: create

    profiles:
        active:
            - db
    servlet:
        multipart:
            max-file-size: 10MB
firebase:
    bucket: am-l-4b665.appspot.com
